# Generated by Django 4.2.6 on 2023-12-01 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc', models.FloatField(null=True)),
                ('basic', models.FloatField(null=True)),
                ('house_rent_allowance', models.IntegerField(null=True)),
                ('conveyance_allowance', models.IntegerField(null=True)),
                ('medical_allowance', models.IntegerField(null=True)),
                ('statutory_bonus', models.IntegerField(null=True)),
                ('special_allowance', models.IntegerField(null=True)),
                ('gratuity', models.IntegerField(null=True)),
                ('gross_earning', models.IntegerField(null=True)),
                ('paid_days', models.IntegerField(null=True)),
                ('in_words', models.CharField(max_length=250, null=True)),
                ('monthly', models.IntegerField(null=True)),
                ('professional_tax', models.IntegerField(null=True)),
                ('ESIC', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500, null=True)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('explanation', models.CharField(max_length=1500, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='employeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('othre_degree', models.CharField(max_length=100, null=True)),
                ('clg_name', models.CharField(max_length=200, null=True)),
                ('specification', models.CharField(max_length=100, null=True)),
                ('percentage', models.CharField(max_length=30, null=True)),
                ('yop', models.DateField(null=True)),
                ('university', models.CharField(max_length=200, null=True)),
                ('other_pdf', models.FileField(default='', upload_to='signup/pdfs')),
                ('university_ug', models.CharField(max_length=200, null=True)),
                ('clg_name_ug', models.CharField(max_length=120, null=True)),
                ('percentage_ug', models.CharField(max_length=20, null=True)),
                ('courseug', models.CharField(max_length=100, null=True)),
                ('yop_ug', models.DateField(null=True)),
                ('ug_pdf', models.FileField(default='', upload_to='signup/pdfs')),
                ('university_pu', models.CharField(max_length=200, null=True)),
                ('coursepu', models.CharField(max_length=50, null=True)),
                ('clg_name_pu', models.CharField(max_length=120, null=True)),
                ('percentage_pu', models.CharField(max_length=20, null=True)),
                ('yop_pu', models.DateField(null=True)),
                ('pu_pdf', models.FileField(default='', upload_to='signup/pdfs')),
                ('university_school', models.CharField(max_length=200, null=True)),
                ('courseschool', models.CharField(max_length=100)),
                ('yop_scchool', models.DateField(null=True)),
                ('clg_name_school', models.CharField(max_length=120, null=True)),
                ('percentage_school', models.CharField(max_length=20, null=True)),
                ('school_pdf', models.FileField(default='', upload_to='signup/pdfs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='employeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.IntegerField()),
                ('email', models.EmailField(max_length=30, null=True)),
                ('designation', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('joining_date', models.DateField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('employee_code', models.CharField(max_length=30, null=True, primary_key=0)),
                ('pan_no', models.CharField(max_length=30, null=True)),
                ('adhar_no', models.CharField(max_length=30, null=True)),
                ('alter_phone', models.IntegerField(default=0)),
                ('alternate_email', models.EmailField(max_length=30, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('name_as_per_bank', models.CharField(max_length=150, null=True)),
                ('name_of_bank', models.CharField(max_length=150, null=True)),
                ('ifsc', models.CharField(max_length=30, null=True)),
                ('acc_no', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(default='', upload_to='signup/images')),
                ('twiter', models.CharField(max_length=200, null=True)),
                ('facebook', models.CharField(max_length=200, null=True)),
                ('instagram', models.CharField(max_length=200, null=True)),
                ('linkedin', models.CharField(max_length=200, null=True)),
                ('job_tittle', models.CharField(max_length=150, null=True)),
                ('job_type', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('pre_company_name', models.CharField(max_length=200, null=True)),
                ('payslip_pdf', models.FileField(default='', upload_to='signup/pdfs')),
                ('experience_pdf', models.FileField(default='', upload_to='signup/pdfs')),
                ('any_other_pdf', models.FileField(default='', upload_to='signup/pdfs')),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(null=True)),
                ('checkout_time', models.DateTimeField(null=True)),
                ('duration', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
