# Generated by Django 4.2.6 on 2023-12-04 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_leaverequests_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequests',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.employeedetails'),
        ),
    ]
