# Generated by Django 4.2.6 on 2023-12-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_leaverequests_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequests',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.employeedetails'),
        ),
    ]
